import os


def _base_url() -> str:
    return os.getenv("IMAGE_BASE_URL", "https://cdn.cs2c.app")


def get_image_url(path: str) -> str:
    return f"{_base_url()}/images/{path}_png.png"


def get_image_url_svg(path: str) -> str:
    return f"{_base_url()}/images/{path}.svg"


LANGUAGES: list[dict[str, str]] = [
    {"language": "english", "folder": "en"},
    {"language": "schinese", "folder": "zh-CN"},
    {"language": "brazilian", "folder": "pt-BR"},
    {"language": "russian", "folder": "ru"},
    {"language": "spanish", "folder": "es-ES"},
    {"language": "bulgarian", "folder": "bg"},
    {"language": "czech", "folder": "cs"},
    {"language": "danish", "folder": "da"},
    {"language": "dutch", "folder": "nl"},
    {"language": "finnish", "folder": "fi"},
    {"language": "french", "folder": "fr"},
    {"language": "german", "folder": "de"},
    {"language": "greek", "folder": "el"},
    {"language": "hungarian", "folder": "hu"},
    {"language": "italian", "folder": "it"},
    {"language": "japanese", "folder": "ja"},
    {"language": "koreana", "folder": "ko"},
    {"language": "latam", "folder": "es-MX"},
    {"language": "norwegian", "folder": "no"},
    {"language": "polish", "folder": "pl"},
    {"language": "portuguese", "folder": "pt-PT"},
    {"language": "romanian", "folder": "ro"},
    {"language": "swedish", "folder": "sv"},
    {"language": "tchinese", "folder": "zh-TW"},
    {"language": "thai", "folder": "th"},
    {"language": "turkish", "folder": "tr"},
    {"language": "ukrainian", "folder": "uk"},
    {"language": "vietnamese", "folder": "vi"},
]


RARE_SPECIAL = {
    "set_community_19_unusual": {
        "[slick_plaid_purple]slick_gloves": 1,
        "[slick_snakeskin_white]slick_gloves": 1,
        "[slick_stitched_green_grey]slick_gloves": 1,
        "[slick_stitched_black_orange]slick_gloves": 1,

        "[handwrap_leathery_fabric_blue_skulls]leather_handwraps": 1,
        "[handwrap_leathery_fabric_geometric_blue]leather_handwraps": 1,
        "[handwrap_leathery_fabric_green_camo]leather_handwraps": 1,
        "[handwrap_leathery_ducttape]leather_handwraps": 1,

        "[bloodhound_hydra_case_hardened]studded_hydra_gloves": 1,
        "[bloodhound_hydra_black_green]studded_hydra_gloves": 1,
        "[bloodhound_hydra_snakeskin_brass]studded_hydra_gloves": 1,
        "[bloodhound_hydra_green_leather_mesh_brass]studded_hydra_gloves": 1,

        "[motorcycle_choco_boom]motorcycle_gloves": 1,
        "[motorcycle_trigrid_blue]motorcycle_gloves": 1,
        "[motorcycle_basic_green_orange]motorcycle_gloves": 1,
        "[motorcycle_yellow_camo]motorcycle_gloves": 1,

        "[specialist_webs_red]specialist_gloves": 1,
        "[specialist_winterhex]specialist_gloves": 1,
        "[specialist_fade]specialist_gloves": 1,
        "[specialist_forest_brown]specialist_gloves": 1,

        "[sporty_blue_pink]sporty_gloves": 1,
        "[sporty_poison_frog_blue_white]sporty_gloves": 1,
        "[sporty_black_webbing_yellow]sporty_gloves": 1,
        "[sporty_poison_frog_red_green]sporty_gloves": 1,
    },
    "community_case_6_unusual": {
        "[am_marble_fade]weapon_bayonet": 1,
        "[an_tiger_orange]weapon_bayonet": 1,
        "[am_ruby_marbleized]weapon_bayonet": 1,
        "[am_sapphire_marbleized]weapon_bayonet": 1,
        "[am_blackpearl_marbleized]weapon_bayonet": 1,
        "[am_doppler_phase1]weapon_bayonet": 1,
        "[am_doppler_phase2]weapon_bayonet": 1,
        "[am_doppler_phase3]weapon_bayonet": 1,
        "[am_doppler_phase4]weapon_bayonet": 1,
        "[aq_damascus]weapon_bayonet": 1,
        "[so_purple]weapon_bayonet": 1,
        "[aq_steel_knife]weapon_bayonet": 1,

        "[am_marble_fade]weapon_knife_flip": 1,
        "[an_tiger_orange]weapon_knife_flip": 1,
        "[am_ruby_marbleized]weapon_knife_flip": 1,
        "[am_sapphire_marbleized]weapon_knife_flip": 1,
        "[am_blackpearl_marbleized]weapon_knife_flip": 1,
        "[am_doppler_phase1]weapon_knife_flip": 1,
        "[am_doppler_phase2]weapon_knife_flip": 1,
        "[am_doppler_phase3]weapon_knife_flip": 1,
        "[am_doppler_phase4]weapon_knife_flip": 1,
        "[aq_damascus]weapon_knife_flip": 1,
        "[so_purple]weapon_knife_flip": 1,
        "[aq_steel_knife]weapon_knife_flip": 1,

        "[am_marble_fade]weapon_knife_gut": 1,
        "[an_tiger_orange]weapon_knife_gut": 1,
        "[am_ruby_marbleized]weapon_knife_gut": 1,
        "[am_sapphire_marbleized]weapon_knife_gut": 1,
        "[am_blackpearl_marbleized]weapon_knife_gut": 1,
        "[am_doppler_phase1]weapon_knife_gut": 1,
        "[am_doppler_phase2]weapon_knife_gut": 1,
        "[am_doppler_phase3]weapon_knife_gut": 1,
        "[am_doppler_phase4]weapon_knife_gut": 1,
        "[aq_damascus]weapon_knife_gut": 1,
        "[so_purple]weapon_knife_gut": 1,
        "[aq_steel_knife]weapon_knife_gut": 1,

        "[am_marble_fade]weapon_knife_karambit": 1,
        "[an_tiger_orange]weapon_knife_karambit": 1,
        "[am_ruby_marbleized]weapon_knife_karambit": 1,
        "[am_sapphire_marbleized]weapon_knife_karambit": 1,
        "[am_blackpearl_marbleized]weapon_knife_karambit": 1,
        "[am_doppler_phase1]weapon_knife_karambit": 1,
        "[am_doppler_phase2]weapon_knife_karambit": 1,
        "[am_doppler_phase3]weapon_knife_karambit": 1,
        "[am_doppler_phase4]weapon_knife_karambit": 1,
        "[aq_damascus]weapon_knife_karambit": 1,
        "[so_purple]weapon_knife_karambit": 1,
        "[aq_steel_knife]weapon_knife_karambit": 1,

        "[am_marble_fade]weapon_knife_m9_bayonet": 1,
        "[an_tiger_orange]weapon_knife_m9_bayonet": 1,
        "[am_ruby_marbleized]weapon_knife_m9_bayonet": 1,
        "[am_sapphire_marbleized]weapon_knife_m9_bayonet": 1,
        "[am_blackpearl_marbleized]weapon_knife_m9_bayonet": 1,
        "[am_doppler_phase1]weapon_knife_m9_bayonet": 1,
        "[am_doppler_phase2]weapon_knife_m9_bayonet": 1,
        "[am_doppler_phase3]weapon_knife_m9_bayonet": 1,
        "[am_doppler_phase4]weapon_knife_m9_bayonet": 1,
        "[aq_damascus_90]weapon_knife_m9_bayonet": 1,
        "[so_purple]weapon_knife_m9_bayonet": 1,
        "[aq_steel_knife]weapon_knife_m9_bayonet": 1,
    },
    "unusual_revolving_list": {
        "[vanilla]weapon_bayonet": 1,
        "[aa_fade]weapon_bayonet": 1,
        "[am_zebra]weapon_bayonet": 1,
        "[aq_oiled]weapon_bayonet": 1,
        "[so_night]weapon_bayonet": 1,
        "[aq_blued]weapon_bayonet": 1,
        "[hy_webs]weapon_bayonet": 1,
        "[aq_forced]weapon_bayonet": 1,
        "[sp_dapple]weapon_bayonet": 1,
        "[sp_mesh_tan]weapon_bayonet": 1,
        "[hy_forest_boreal]weapon_bayonet": 1,
        "[sp_tape_urban]weapon_bayonet": 1,
        "[hy_ddpat]weapon_bayonet": 1,

        "[vanilla]weapon_knife_flip": 1,
        "[aa_fade]weapon_knife_flip": 1,
        "[am_zebra]weapon_knife_flip": 1,
        "[aq_oiled]weapon_knife_flip": 1,
        "[so_night]weapon_knife_flip": 1,
        "[aq_blued]weapon_knife_flip": 1,
        "[hy_webs]weapon_knife_flip": 1,
        "[aq_forced]weapon_knife_flip": 1,
        "[sp_dapple]weapon_knife_flip": 1,
        "[sp_mesh_tan]weapon_knife_flip": 1,
        "[hy_forest_boreal]weapon_knife_flip": 1,
        "[sp_tape_urban]weapon_knife_flip": 1,
        "[hy_ddpat]weapon_knife_flip": 1,

        "[vanilla]weapon_knife_gut": 1,
        "[aa_fade]weapon_knife_gut": 1,
        "[am_zebra]weapon_knife_gut": 1,
        "[aq_oiled]weapon_knife_gut": 1,
        "[so_night]weapon_knife_gut": 1,
        "[aq_blued]weapon_knife_gut": 1,
        "[hy_webs]weapon_knife_gut": 1,
        "[aq_forced]weapon_knife_gut": 1,
        "[sp_dapple]weapon_knife_gut": 1,
        "[sp_mesh_tan]weapon_knife_gut": 1,
        "[hy_forest_boreal]weapon_knife_gut": 1,
        "[sp_tape_urban]weapon_knife_gut": 1,
        "[hy_ddpat]weapon_knife_gut": 1,

        "[vanilla]weapon_knife_karambit": 1,
        "[aa_fade]weapon_knife_karambit": 1,
        "[am_zebra]weapon_knife_karambit": 1,
        "[aq_oiled]weapon_knife_karambit": 1,
        "[so_night]weapon_knife_karambit": 1,
        "[aq_blued]weapon_knife_karambit": 1,
        "[hy_webs]weapon_knife_karambit": 1,
        "[aq_forced]weapon_knife_karambit": 1,
        "[sp_dapple]weapon_knife_karambit": 1,
        "[sp_mesh_tan]weapon_knife_karambit": 1,
        "[hy_forest_boreal]weapon_knife_karambit": 1,
        "[sp_tape_urban]weapon_knife_karambit": 1,
        "[hy_ddpat]weapon_knife_karambit": 1,

        "[vanilla]weapon_knife_m9_bayonet": 1,
        "[aa_fade]weapon_knife_m9_bayonet": 1,
        "[am_zebra]weapon_knife_m9_bayonet": 1,
        "[aq_oiled]weapon_knife_m9_bayonet": 1,
        "[so_night]weapon_knife_m9_bayonet": 1,
        "[aq_blued]weapon_knife_m9_bayonet": 1,
        "[hy_webs]weapon_knife_m9_bayonet": 1,
        "[aq_forced]weapon_knife_m9_bayonet": 1,
        "[sp_dapple]weapon_knife_m9_bayonet": 1,
        "[sp_mesh_tan]weapon_knife_m9_bayonet": 1,
        "[hy_forest_boreal]weapon_knife_m9_bayonet": 1,
        "[sp_tape_urban]weapon_knife_m9_bayonet": 1,
        "[hy_ddpat]weapon_knife_m9_bayonet": 1,
    },
    "set_glove_3_unusual": {
        "[operation10_poison_frog_black_yellow]studded_brokenfang_gloves": 1,
        "[operation10_snakeskin_black]studded_brokenfang_gloves": 1,
        "[operation10_floral]studded_brokenfang_gloves": 1,
        "[operation10_metalic_green]studded_brokenfang_gloves": 1,

        "[slick_jaguar_white]slick_gloves": 1,
        "[slick_stitched_black_white]slick_gloves": 1,
        "[slick_rezan]slick_gloves": 1,
        "[slick_jaguar_yellow]slick_gloves": 1,

        "[handwrap_leathery_caution]leather_handwraps": 1,
        "[handwrap_leathery_fabric_giraffe]leather_handwraps": 1,
        "[handwrap_leathery_snakeskin_orange]leather_handwraps": 1,
        "[handwrap_fabric_houndstooth_orange]leather_handwraps": 1,

        "[motorcycle_carbonfiber_red]motorcycle_gloves": 1,
        "[motorcycle_smoke]motorcycle_gloves": 1,
        "[motorcycle_checker_flag_blue_green]motorcycle_gloves": 1,
        "[motorcycle_commando_ksk]motorcycle_gloves": 1,

        "[specialist_fbi]specialist_gloves": 1,
        "[specialist_tiger_orange]specialist_gloves": 1,
        "[specialist_ricksaw_camo]specialist_gloves": 1,
        "[specialist_marble_fade]specialist_gloves": 1,

        "[sporty_slingshot]sporty_gloves": 1,
        "[sporty_houndstooth_red]sporty_gloves": 1,
        "[sporty_jaguar]sporty_gloves": 1,
        "[sporty_hunter]sporty_gloves": 1,
    },
    "gamma2_knives2_unusual": {
        "[am_emerald_marbleized]weapon_knife_survival_bowie": 1,
        "[am_gamma_doppler_phase1]weapon_knife_survival_bowie": 1,
        "[am_gamma_doppler_phase2]weapon_knife_survival_bowie": 1,
        "[am_gamma_doppler_phase3]weapon_knife_survival_bowie": 1,
        "[am_gamma_doppler_phase4]weapon_knife_survival_bowie": 1,
        "[cu_bowie_lore]weapon_knife_survival_bowie": 1,
        "[gs_bowie_autotronic]weapon_knife_survival_bowie": 1,
        "[gs_bowie_black_laminate]weapon_knife_survival_bowie": 1,
        "[am_marked_up_90]weapon_knife_survival_bowie": 1,
        "[hy_ocean_knife_90]weapon_knife_survival_bowie": 1,

        "[am_emerald_marbleized]weapon_knife_butterfly": 1,
        "[am_gamma_doppler_phase1]weapon_knife_butterfly": 1,
        "[am_gamma_doppler_phase2]weapon_knife_butterfly": 1,
        "[am_gamma_doppler_phase3]weapon_knife_butterfly": 1,
        "[am_gamma_doppler_phase4]weapon_knife_butterfly": 1,
        "[cu_butterfly_lore]weapon_knife_butterfly": 1,
        "[gs_butterfly_autotronic]weapon_knife_butterfly": 1,
        "[gs_butterfly_black_laminate]weapon_knife_butterfly": 1,
        "[am_marked_up_90]weapon_knife_butterfly": 1,
        "[hy_ocean_knife_90]weapon_knife_butterfly": 1,

        "[am_emerald_marbleized]weapon_knife_falchion": 1,
        "[am_gamma_doppler_phase1]weapon_knife_falchion": 1,
        "[am_gamma_doppler_phase2]weapon_knife_falchion": 1,
        "[am_gamma_doppler_phase3]weapon_knife_falchion": 1,
        "[am_gamma_doppler_phase4]weapon_knife_falchion": 1,
        "[cu_falchion_lore]weapon_knife_falchion": 1,
        "[gs_falchion_autotronic]weapon_knife_falchion": 1,
        "[gs_falchion_black_laminate]weapon_knife_falchion": 1,
        "[am_marked_up_90]weapon_knife_falchion": 1,
        "[hy_ocean_knife_90]weapon_knife_falchion": 1,

        "[am_emerald_marbleized]weapon_knife_tactical": 1,
        "[am_gamma_doppler_phase1]weapon_knife_tactical": 1,
        "[am_gamma_doppler_phase2]weapon_knife_tactical": 1,
        "[am_gamma_doppler_phase3]weapon_knife_tactical": 1,
        "[am_gamma_doppler_phase4]weapon_knife_tactical": 1,
        "[cu_huntsman_lore]weapon_knife_tactical": 1,
        "[gs_huntsman_autotronic]weapon_knife_tactical": 1,
        "[gs_huntsman_black_laminate]weapon_knife_tactical": 1,
        "[am_marked_up_90]weapon_knife_tactical": 1,
        "[hy_ocean_knife_90]weapon_knife_tactical": 1,

        "[am_emerald_marbleized]weapon_knife_push": 1,
        "[am_gamma_doppler_phase1]weapon_knife_push": 1,
        "[am_gamma_doppler_phase2]weapon_knife_push": 1,
        "[am_gamma_doppler_phase3]weapon_knife_push": 1,
        "[am_gamma_doppler_phase4]weapon_knife_push": 1,
        "[cu_push_lore]weapon_knife_push": 1,
        "[gs_push_autotronic]weapon_knife_push": 1,
        "[gs_push_black_laminate]weapon_knife_push": 1,
        "[am_marked_up_90]weapon_knife_push": 1,
        "[hy_ocean_knife_90]weapon_knife_push": 1,
    },
    # crate_xray_p250_lootlist: {
    #     "[cu_xray_p250]weapon_p250": 1,
    # },
    "community_case_3_unusual": {
        "[vanilla]weapon_knife_tactical": 1,
        "[aa_fade]weapon_knife_tactical": 1,
        "[hy_webs]weapon_knife_tactical": 1,
        "[am_zebra]weapon_knife_tactical": 1,
        "[aq_oiled]weapon_knife_tactical": 1,
        "[sp_tape_urban]weapon_knife_tactical": 1,
        "[aq_blued]weapon_knife_tactical": 1,
        "[so_night]weapon_knife_tactical": 1,
        "[aq_forced]weapon_knife_tactical": 1,
        "[hy_ddpat]weapon_knife_tactical": 1,
        "[hy_forest_boreal]weapon_knife_tactical": 1,
        "[sp_dapple]weapon_knife_tactical": 1,
        "[sp_mesh_tan]weapon_knife_tactical": 1,
    },
    "community_case_4_unusual": {
        "[vanilla]weapon_knife_butterfly": 1,
        "[aa_fade]weapon_knife_butterfly": 1,
        "[hy_webs]weapon_knife_butterfly": 1,
        "[am_zebra]weapon_knife_butterfly": 1,
        "[aq_oiled]weapon_knife_butterfly": 1,
        "[sp_tape_urban]weapon_knife_butterfly": 1,
        "[aq_blued]weapon_knife_butterfly": 1,
        "[so_night]weapon_knife_butterfly": 1,
        "[aq_forced]weapon_knife_butterfly": 1,
        "[hy_ddpat]weapon_knife_butterfly": 1,
        "[hy_forest_boreal]weapon_knife_butterfly": 1,
        "[sp_dapple]weapon_knife_butterfly": 1,
        "[sp_mesh_tan]weapon_knife_butterfly": 1,
    },
    "community_case_9_unusual": {
        "[vanilla]weapon_knife_push": 1,
        "[aa_fade]weapon_knife_push": 1,
        "[hy_webs]weapon_knife_push": 1,
        "[am_zebra]weapon_knife_push": 1,
        "[aq_oiled]weapon_knife_push": 1,
        "[sp_tape_urban]weapon_knife_push": 1,
        "[aq_blued]weapon_knife_push": 1,
        "[so_night]weapon_knife_push": 1,
        "[aq_forced]weapon_knife_push": 1,
        "[hy_ddpat]weapon_knife_push": 1,
        "[hy_forest_boreal]weapon_knife_push": 1,
        "[sp_dapple]weapon_knife_push": 1,
        "[sp_mesh_tan]weapon_knife_push": 1,
    },
    "community_case_11_unusual": {
        "[vanilla]weapon_knife_survival_bowie": 1,
        "[aa_fade]weapon_knife_survival_bowie": 1,
        "[hy_webs]weapon_knife_survival_bowie": 1,
        "[am_zebra]weapon_knife_survival_bowie": 1,
        "[aq_oiled]weapon_knife_survival_bowie": 1,
        "[sp_tape_urban]weapon_knife_survival_bowie": 1,
        "[aq_blued]weapon_knife_survival_bowie": 1,
        "[so_night]weapon_knife_survival_bowie": 1,
        "[aq_forced]weapon_knife_survival_bowie": 1,
        "[hy_ddpat]weapon_knife_survival_bowie": 1,
        "[hy_forest_boreal]weapon_knife_survival_bowie": 1,
        "[sp_dapple]weapon_knife_survival_bowie": 1,
        "[sp_mesh_tan]weapon_knife_survival_bowie": 1,
    },
    # The Gamma Collection - The Gamma 2 Collection
    "community_case_13_unusual": {
        "[am_emerald_marbleized]weapon_bayonet": 1,
        "[am_gamma_doppler_phase1]weapon_bayonet": 1,
        "[am_gamma_doppler_phase2]weapon_bayonet": 1,
        "[am_gamma_doppler_phase3]weapon_bayonet": 1,
        "[am_gamma_doppler_phase4]weapon_bayonet": 1,
        "[cu_bayonet_lore]weapon_bayonet": 1,
        "[gs_bayonet_autotronic]weapon_bayonet": 1,
        "[cu_bayonet_stonewash]weapon_bayonet": 1,
        "[am_marked_up]weapon_bayonet": 1,
        "[hy_ocean_knife]weapon_bayonet": 1,

        "[am_emerald_marbleized]weapon_knife_flip": 1,
        "[am_gamma_doppler_phase1]weapon_knife_flip": 1,
        "[am_gamma_doppler_phase2]weapon_knife_flip": 1,
        "[am_gamma_doppler_phase3]weapon_knife_flip": 1,
        "[am_gamma_doppler_phase4]weapon_knife_flip": 1,
        "[cu_flip_lore]weapon_knife_flip": 1,
        "[gs_flip_autotronic]weapon_knife_flip": 1,
        "[cu_flip_stonewash]weapon_knife_flip": 1,
        "[am_marked_up]weapon_knife_flip": 1,
        "[hy_ocean_knife]weapon_knife_flip": 1,

        "[am_emerald_marbleized]weapon_knife_gut": 1,
        "[am_gamma_doppler_phase1]weapon_knife_gut": 1,
        "[am_gamma_doppler_phase2]weapon_knife_gut": 1,
        "[am_gamma_doppler_phase3]weapon_knife_gut": 1,
        "[am_gamma_doppler_phase4]weapon_knife_gut": 1,
        "[cu_gut_lore]weapon_knife_gut": 1,
        "[gs_gut_autotronic]weapon_knife_gut": 1,
        "[cu_gut_stonewash]weapon_knife_gut": 1,
        "[hy_ocean_knife]weapon_knife_gut": 1,
        "[am_marked_up]weapon_knife_gut": 1,

        "[am_emerald_marbleized]weapon_knife_karambit": 1,
        "[am_gamma_doppler_phase1]weapon_knife_karambit": 1,
        "[am_gamma_doppler_phase2]weapon_knife_karambit": 1,
        "[am_gamma_doppler_phase3]weapon_knife_karambit": 1,
        "[am_gamma_doppler_phase4]weapon_knife_karambit": 1,
        "[cu_karam_lore]weapon_knife_karambit": 1,
        "[gs_karam_autotronic]weapon_knife_karambit": 1,
        "[cu_karam_stonewash]weapon_knife_karambit": 1,
        "[am_marked_up_fine]weapon_knife_karambit": 1,
        "[hy_ocean_knife]weapon_knife_karambit": 1,

        "[am_emerald_marbleized]weapon_knife_m9_bayonet": 1,
        "[am_gamma_doppler_phase1]weapon_knife_m9_bayonet": 1,
        "[am_gamma_doppler_phase2]weapon_knife_m9_bayonet": 1,
        "[am_gamma_doppler_phase3]weapon_knife_m9_bayonet": 1,
        "[am_gamma_doppler_phase4]weapon_knife_m9_bayonet": 1,
        "[cu_m9_bay_lore]weapon_knife_m9_bayonet": 1,
        "[gs_m9_bay_autotronic]weapon_knife_m9_bayonet": 1,
        "[cu_m9_bay_stonewash]weapon_knife_m9_bayonet": 1,
        "[hy_ocean_knife_90]weapon_knife_m9_bayonet": 1,
        "[am_marked_up_90]weapon_knife_m9_bayonet": 1,
    },
    "community_case_15_unusual": {
        "[bloodhound_snakeskin_brass]studded_bloodhound_gloves": 1,
        "[bloodhound_metallic]studded_bloodhound_gloves": 1,
        "[bloodhound_black_silver]studded_bloodhound_gloves": 1,
        "[bloodhound_guerrilla]studded_bloodhound_gloves": 1,

        "[slick_red]slick_gloves": 1,
        "[slick_military]slick_gloves": 1,
        "[slick_black]slick_gloves": 1,
        "[slick_snakeskin_yellow]slick_gloves": 1,

        "[handwrap_red_slaughter]leather_handwraps": 1,
        "[handwrap_fabric_orange_camo]leather_handwraps": 1,
        "[handwrap_camo_grey]leather_handwraps": 1,
        "[handwrap_leathery]leather_handwraps": 1,

        "[motorcycle_triangle_blue]motorcycle_gloves": 1,
        "[motorcycle_mono_boom]motorcycle_gloves": 1,
        "[motorcycle_mint_triangle]motorcycle_gloves": 1,
        "[motorcycle_basic_black]motorcycle_gloves": 1,

        "[specialist_kimono_diamonds_red]specialist_gloves": 1,
        "[specialist_emerald_web]specialist_gloves": 1,
        "[specialist_ddpat_green_camo]specialist_gloves": 1,
        "[specialist_orange_white]specialist_gloves": 1,

        "[sporty_light_blue]sporty_gloves": 1,
        "[sporty_green]sporty_gloves": 1,
        "[sporty_military]sporty_gloves": 1,
        "[sporty_purple]sporty_gloves": 1,
    },
    "spectrum_unusual": {
        "[am_marble_fade]weapon_knife_survival_bowie": 1,
        "[an_tiger_orange]weapon_knife_survival_bowie": 1,
        "[am_ruby_marbleized]weapon_knife_survival_bowie": 1,
        "[am_sapphire_marbleized]weapon_knife_survival_bowie": 1,
        "[am_blackpearl_marbleized]weapon_knife_survival_bowie": 1,
        "[am_doppler_phase1]weapon_knife_survival_bowie": 1,
        "[am_doppler_phase2]weapon_knife_survival_bowie": 1,
        "[am_doppler_phase3]weapon_knife_survival_bowie": 1,
        "[am_doppler_phase4]weapon_knife_survival_bowie": 1,
        "[aq_damascus_90]weapon_knife_survival_bowie": 1,
        "[so_purple]weapon_knife_survival_bowie": 1,
        "[aq_steel_knife]weapon_knife_survival_bowie": 1,

        "[am_marble_fade]weapon_knife_butterfly": 1,
        "[an_tiger_orange]weapon_knife_butterfly": 1,
        "[am_ruby_marbleized]weapon_knife_butterfly": 1,
        "[am_sapphire_marbleized_b]weapon_knife_butterfly": 1,
        "[am_blackpearl_marbleized_b]weapon_knife_butterfly": 1,
        "[am_doppler_phase1]weapon_knife_butterfly": 1,
        "[am_doppler_phase2_b]weapon_knife_butterfly": 1,
        "[am_doppler_phase3]weapon_knife_butterfly": 1,
        "[am_doppler_phase4]weapon_knife_butterfly": 1,
        "[aq_damascus_90]weapon_knife_butterfly": 1,
        "[so_purple]weapon_knife_butterfly": 1,
        "[aq_steel_knife]weapon_knife_butterfly": 1,

        "[am_marble_fade]weapon_knife_falchion": 1,
        "[an_tiger_orange]weapon_knife_falchion": 1,
        "[am_ruby_marbleized]weapon_knife_falchion": 1,
        "[am_sapphire_marbleized]weapon_knife_falchion": 1,
        "[am_blackpearl_marbleized]weapon_knife_falchion": 1,
        "[am_doppler_phase1]weapon_knife_falchion": 1,
        "[am_doppler_phase2]weapon_knife_falchion": 1,
        "[am_doppler_phase3]weapon_knife_falchion": 1,
        "[am_doppler_phase4]weapon_knife_falchion": 1,
        "[aq_damascus_90]weapon_knife_falchion": 1,
        "[so_purple_falchion]weapon_knife_falchion": 1,
        "[aq_steel_knife]weapon_knife_falchion": 1,

        "[am_marble_fade]weapon_knife_tactical": 1,
        "[an_tiger_orange]weapon_knife_tactical": 1,
        "[am_ruby_marbleized]weapon_knife_tactical": 1,
        "[am_sapphire_marbleized]weapon_knife_tactical": 1,
        "[am_blackpearl_marbleized]weapon_knife_tactical": 1,
        "[am_doppler_phase1]weapon_knife_tactical": 1,
        "[am_doppler_phase2]weapon_knife_tactical": 1,
        "[am_doppler_phase3]weapon_knife_tactical": 1,
        "[am_doppler_phase4]weapon_knife_tactical": 1,
        "[aq_damascus_90]weapon_knife_tactical": 1,
        "[cu_purple_huntsman]weapon_knife_tactical": 1,
        "[aq_steel_knife]weapon_knife_tactical": 1,

        "[am_marble_fade]weapon_knife_push": 1,
        "[an_tiger_orange]weapon_knife_push": 1,
        "[am_ruby_marbleized]weapon_knife_push": 1,
        "[am_sapphire_marbleized_b]weapon_knife_push": 1,
        "[am_blackpearl_marbleized_b]weapon_knife_push": 1,
        "[am_doppler_phase1]weapon_knife_push": 1,
        "[am_doppler_phase2_b]weapon_knife_push": 1,
        "[am_doppler_phase3]weapon_knife_push": 1,
        "[am_doppler_phase4]weapon_knife_push": 1,
        "[aq_damascus_90]weapon_knife_push": 1,
        "[so_purple]weapon_knife_push": 1,
        "[aq_steel_knife]weapon_knife_push": 1,
    },
    "community_case_8_unusual": {
        "[vanilla]weapon_knife_falchion": 1,
        "[aa_fade]weapon_knife_falchion": 1,
        "[hy_webs]weapon_knife_falchion": 1,
        "[am_zebra]weapon_knife_falchion": 1,
        "[aq_oiled]weapon_knife_falchion": 1,
        "[sp_tape_urban]weapon_knife_falchion": 1,
        "[aq_blued]weapon_knife_falchion": 1,
        "[so_night]weapon_knife_falchion": 1,
        "[aq_forced]weapon_knife_falchion": 1,
        "[hy_ddpat]weapon_knife_falchion": 1,
        "[hy_forest_boreal]weapon_knife_falchion": 1,
        "[sp_dapple]weapon_knife_falchion": 1,
        "[sp_mesh_tan]weapon_knife_falchion": 1,
    },
    "set_community_24_unusual": {
        "[vanilla]weapon_knife_css": 1,
        "[aa_fade]weapon_knife_css": 1,
        "[hy_webs]weapon_knife_css": 1,
        "[am_zebra]weapon_knife_css": 1,
        "[aq_oiled]weapon_knife_css": 1,
        "[sp_tape_urban]weapon_knife_css": 1,
        "[aq_blued]weapon_knife_css": 1,
        "[sp_nightstripe]weapon_knife_css": 1,
        "[aq_forced]weapon_knife_css": 1,
        "[hy_ddpat]weapon_knife_css": 1,
        "[hy_forest_boreal]weapon_knife_css": 1,
        "[sp_dapple]weapon_knife_css": 1,
        "[sp_mesh_tan]weapon_knife_css": 1,
    },
    "set_community_23_unusual": {
        "[vanilla]weapon_knife_outdoor": 1,
        "[aa_fade]weapon_knife_outdoor": 1,
        "[hy_webs]weapon_knife_outdoor": 1,
        "[am_zebra]weapon_knife_outdoor": 1,
        "[aq_oiled]weapon_knife_outdoor": 1,
        "[sp_tape_urban]weapon_knife_outdoor": 1,
        "[aq_blued]weapon_knife_outdoor": 1,
        "[sp_nightstripe]weapon_knife_outdoor": 1,
        "[aq_forced]weapon_knife_outdoor": 1,
        "[hy_ddpat]weapon_knife_outdoor": 1,
        "[hy_forest_boreal]weapon_knife_outdoor": 1,
        "[sp_dapple]weapon_knife_outdoor": 1,
        "[sp_mesh_tan]weapon_knife_outdoor": 1,

        "[vanilla]weapon_knife_cord": 1,
        "[aa_fade]weapon_knife_cord": 1,
        "[hy_webs]weapon_knife_cord": 1,
        "[am_zebra]weapon_knife_cord": 1,
        "[aq_oiled]weapon_knife_cord": 1,
        "[sp_tape_urban]weapon_knife_cord": 1,
        "[aq_blued]weapon_knife_cord": 1,
        "[sp_nightstripe]weapon_knife_cord": 1,
        "[aq_forced]weapon_knife_cord": 1,
        "[hy_ddpat]weapon_knife_cord": 1,
        "[hy_forest_boreal]weapon_knife_cord": 1,
        "[sp_dapple]weapon_knife_cord": 1,
        "[sp_mesh_tan]weapon_knife_cord": 1,

        "[vanilla]weapon_knife_skeleton": 1,
        "[aa_fade]weapon_knife_skeleton": 1,
        "[hy_webs]weapon_knife_skeleton": 1,
        "[am_zebra]weapon_knife_skeleton": 1,
        "[aq_oiled]weapon_knife_skeleton": 1,
        "[sp_tape_urban]weapon_knife_skeleton": 1,
        "[aq_blued]weapon_knife_skeleton": 1,
        "[sp_nightstripe]weapon_knife_skeleton": 1,
        "[aq_forced]weapon_knife_skeleton": 1,
        "[hy_ddpat]weapon_knife_skeleton": 1,
        "[hy_forest_boreal]weapon_knife_skeleton": 1,
        "[sp_dapple]weapon_knife_skeleton": 1,
        "[sp_mesh_tan]weapon_knife_skeleton": 1,

        "[vanilla]weapon_knife_canis": 1,
        "[aa_fade]weapon_knife_canis": 1,
        "[hy_webs]weapon_knife_canis": 1,
        "[am_zebra]weapon_knife_canis": 1,
        "[aq_oiled]weapon_knife_canis": 1,
        "[sp_tape_urban]weapon_knife_canis": 1,
        "[aq_blued]weapon_knife_canis": 1,
        "[sp_nightstripe]weapon_knife_canis": 1,
        "[aq_forced]weapon_knife_canis": 1,
        "[hy_ddpat]weapon_knife_canis": 1,
        "[hy_forest_boreal]weapon_knife_canis": 1,
        "[sp_dapple]weapon_knife_canis": 1,
        "[sp_mesh_tan]weapon_knife_canis": 1,
    },
    "set_community_22_unusual": {
        "[vanilla]weapon_knife_gypsy_jackknife": 1,
        "[am_marble_fade]weapon_knife_gypsy_jackknife": 1,
        "[an_tiger_orange]weapon_knife_gypsy_jackknife": 1,
        "[am_ruby_marbleized]weapon_knife_gypsy_jackknife": 1,
        "[am_sapphire_marbleized]weapon_knife_gypsy_jackknife": 1,
        "[am_blackpearl_marbleized]weapon_knife_gypsy_jackknife": 1,
        "[am_doppler_phase1]weapon_knife_gypsy_jackknife": 1,
        "[am_doppler_phase2]weapon_knife_gypsy_jackknife": 1,
        "[am_doppler_phase3]weapon_knife_gypsy_jackknife": 1,
        "[am_doppler_phase4]weapon_knife_gypsy_jackknife": 1,
        "[aq_damascus_prisma]weapon_knife_gypsy_jackknife": 1,
        "[so_purple]weapon_knife_gypsy_jackknife": 1,
        "[aq_steel_knife]weapon_knife_gypsy_jackknife": 1,

        "[vanilla]weapon_knife_stiletto": 1,
        "[am_marble_fade]weapon_knife_stiletto": 1,
        "[an_tiger_orange]weapon_knife_stiletto": 1,
        "[am_ruby_marbleized]weapon_knife_stiletto": 1,
        "[am_sapphire_marbleized]weapon_knife_stiletto": 1,
        "[am_blackpearl_marbleized]weapon_knife_stiletto": 1,
        "[am_doppler_phase1]weapon_knife_stiletto": 1,
        "[am_doppler_phase2]weapon_knife_stiletto": 1,
        "[am_doppler_phase3]weapon_knife_stiletto": 1,
        "[am_doppler_phase4]weapon_knife_stiletto": 1,
        "[aq_damascus_prisma]weapon_knife_stiletto": 1,
        "[so_purple]weapon_knife_stiletto": 1,
        "[aq_steel_knife]weapon_knife_stiletto": 1,

        "[vanilla]weapon_knife_widowmaker": 1,
        "[am_marble_fade_widow]weapon_knife_widowmaker": 1,
        "[an_tiger_orange]weapon_knife_widowmaker": 1,
        "[am_ruby_marbleized]weapon_knife_widowmaker": 1,
        "[am_sapphire_marbleized]weapon_knife_widowmaker": 1,
        "[am_blackpearl_marbleized]weapon_knife_widowmaker": 1,
        "[am_doppler_phase1_widow]weapon_knife_widowmaker": 1,
        "[am_doppler_phase2_widow]weapon_knife_widowmaker": 1,
        "[am_doppler_phase3_widow]weapon_knife_widowmaker": 1,
        "[am_doppler_phase4_widow]weapon_knife_widowmaker": 1,
        "[aq_damascus_widow]weapon_knife_widowmaker": 1,
        "[so_purple]weapon_knife_widowmaker": 1,
        "[aq_steel_knife]weapon_knife_widowmaker": 1,

        "[vanilla]weapon_knife_ursus": 1,
        "[am_marble_fade]weapon_knife_ursus": 1,
        "[an_tiger_orange]weapon_knife_ursus": 1,
        "[am_ruby_marbleized]weapon_knife_ursus": 1,
        "[am_sapphire_marbleized]weapon_knife_ursus": 1,
        "[am_blackpearl_marbleized]weapon_knife_ursus": 1,
        "[am_doppler_phase1]weapon_knife_ursus": 1,
        "[am_doppler_phase2]weapon_knife_ursus": 1,
        "[am_doppler_phase3]weapon_knife_ursus": 1,
        "[am_doppler_phase4]weapon_knife_ursus": 1,
        "[aq_damascus_prisma]weapon_knife_ursus": 1,
        "[so_purple]weapon_knife_ursus": 1,
        "[aq_steel_knife]weapon_knife_ursus": 1,
    },
    "set_community_20_unusual": {
        "[vanilla]weapon_knife_gypsy_jackknife": 1,
        "[aa_fade]weapon_knife_gypsy_jackknife": 1,
        "[hy_webs]weapon_knife_gypsy_jackknife": 1,
        "[am_zebra]weapon_knife_gypsy_jackknife": 1,
        "[aq_oiled]weapon_knife_gypsy_jackknife": 1,
        "[sp_tape_urban]weapon_knife_gypsy_jackknife": 1,
        "[aq_blued]weapon_knife_gypsy_jackknife": 1,
        "[sp_nightstripe]weapon_knife_gypsy_jackknife": 1,
        "[aq_forced]weapon_knife_gypsy_jackknife": 1,
        "[hy_ddpat]weapon_knife_gypsy_jackknife": 1,
        "[hy_forest_boreal]weapon_knife_gypsy_jackknife": 1,
        "[sp_dapple]weapon_knife_gypsy_jackknife": 1,
        "[sp_mesh_tan]weapon_knife_gypsy_jackknife": 1,

        "[vanilla]weapon_knife_stiletto": 1,
        "[aa_fade]weapon_knife_stiletto": 1,
        "[hy_webs]weapon_knife_stiletto": 1,
        "[am_zebra]weapon_knife_stiletto": 1,
        "[aq_oiled]weapon_knife_stiletto": 1,
        "[sp_tape_urban]weapon_knife_stiletto": 1,
        "[aq_blued]weapon_knife_stiletto": 1,
        "[sp_nightstripe]weapon_knife_stiletto": 1,
        "[aq_forced]weapon_knife_stiletto": 1,
        "[hy_ddpat]weapon_knife_stiletto": 1,
        "[hy_forest_boreal]weapon_knife_stiletto": 1,
        "[sp_dapple]weapon_knife_stiletto": 1,
        "[sp_mesh_tan]weapon_knife_stiletto": 1,

        "[vanilla]weapon_knife_widowmaker": 1,
        "[aa_fade]weapon_knife_widowmaker": 1,
        "[hy_webs]weapon_knife_widowmaker": 1,
        "[am_zebra]weapon_knife_widowmaker": 1,
        "[aq_oiled]weapon_knife_widowmaker": 1,
        "[sp_tape_urban]weapon_knife_widowmaker": 1,
        "[aq_blued]weapon_knife_widowmaker": 1,
        "[sp_nightstripe]weapon_knife_widowmaker": 1,
        "[aq_forced]weapon_knife_widowmaker": 1,
        "[hy_ddpat]weapon_knife_widowmaker": 1,
        "[hy_forest_boreal]weapon_knife_widowmaker": 1,
        "[sp_dapple]weapon_knife_widowmaker": 1,
        "[sp_mesh_tan]weapon_knife_widowmaker": 1,

        "[vanilla]weapon_knife_ursus": 1,
        "[aa_fade]weapon_knife_ursus": 1,
        "[hy_webs]weapon_knife_ursus": 1,
        "[am_zebra]weapon_knife_ursus": 1,
        "[aq_oiled]weapon_knife_ursus": 1,
        "[sp_tape_urban]weapon_knife_ursus": 1,
        "[aq_blued]weapon_knife_ursus": 1,
        "[sp_nightstripe]weapon_knife_ursus": 1,
        "[aq_forced]weapon_knife_ursus": 1,
        "[hy_ddpat]weapon_knife_ursus": 1,
        "[hy_forest_boreal]weapon_knife_ursus": 1,
        "[sp_dapple]weapon_knife_ursus": 1,
        "[sp_mesh_tan]weapon_knife_ursus": 1,
    },
    "set_community_33_unusual": {
        "[vanilla]weapon_knife_kukri": 1,
        "[aa_fade]weapon_knife_kukri": 1,
        "[am_zebra]weapon_knife_kukri": 1,
        "[aq_blued]weapon_knife_kukri": 1,
        "[aq_forced]weapon_knife_kukri": 1,
        "[aq_oiled]weapon_knife_kukri": 1,
        "[hy_ddpat]weapon_knife_kukri": 1,
        "[hy_forest_boreal]weapon_knife_kukri": 1,
        "[hy_webs]weapon_knife_kukri": 1,
        "[sp_dapple]weapon_knife_kukri": 1,
        "[sp_mesh_tan]weapon_knife_kukri": 1,
        "[sp_nightstripe]weapon_knife_kukri": 1,
        "[sp_tape_urban]weapon_knife_kukri": 1,
    },
    "set_community_35_unusual": {
        "[vanilla]weapon_knife_canis": 1,
        "[am_marble_fade]weapon_knife_canis": 1,
        "[an_tiger_orange]weapon_knife_canis": 1,
        "[am_ruby_marbleized]weapon_knife_canis": 1,
        "[am_sapphire_marbleized]weapon_knife_canis": 1,
        "[am_blackpearl_marbleized]weapon_knife_canis": 1,
        "[am_doppler_phase1]weapon_knife_canis": 1,
        "[am_doppler_phase2]weapon_knife_canis": 1,
        "[am_doppler_phase3]weapon_knife_canis": 1,
        "[am_doppler_phase4]weapon_knife_canis": 1,
        "[aq_damascus]weapon_knife_canis": 1,
        "[so_purple]weapon_knife_canis": 1,
        "[aq_steel_knife]weapon_knife_canis": 1,

        "[vanilla]weapon_knife_skeleton": 1,
        "[am_marble_fade]weapon_knife_skeleton": 1,
        "[an_tiger_orange]weapon_knife_skeleton": 1,
        "[am_ruby_marbleized]weapon_knife_skeleton": 1,
        "[am_sapphire_marbleized]weapon_knife_skeleton": 1,
        "[am_blackpearl_marbleized]weapon_knife_skeleton": 1,
        "[am_doppler_phase1]weapon_knife_skeleton": 1,
        "[am_doppler_phase2]weapon_knife_skeleton": 1,
        "[am_doppler_phase3]weapon_knife_skeleton": 1,
        "[am_doppler_phase4]weapon_knife_skeleton": 1,
        "[aq_damascus]weapon_knife_skeleton": 1,
        "[so_purple]weapon_knife_skeleton": 1,
        "[aq_steel_knife]weapon_knife_skeleton": 1,

        "[vanilla]weapon_knife_cord": 1,
        "[am_marble_fade]weapon_knife_cord": 1,
        "[an_tiger_orange]weapon_knife_cord": 1,
        "[am_ruby_marbleized]weapon_knife_cord": 1,
        "[am_sapphire_marbleized]weapon_knife_cord": 1,
        "[am_blackpearl_marbleized]weapon_knife_cord": 1,
        "[am_doppler_phase1]weapon_knife_cord": 1,
        "[am_doppler_phase2]weapon_knife_cord": 1,
        "[am_doppler_phase3]weapon_knife_cord": 1,
        "[am_doppler_phase4]weapon_knife_cord": 1,
        "[aq_damascus]weapon_knife_cord": 1,
        "[so_purple_falchion]weapon_knife_cord": 1,
        "[aq_steel_knife]weapon_knife_cord": 1,

        "[vanilla]weapon_knife_outdoor": 1,
        "[am_marble_fade]weapon_knife_outdoor": 1,
        "[an_tiger_orange]weapon_knife_outdoor": 1,
        "[am_ruby_marbleized]weapon_knife_outdoor": 1,
        "[am_sapphire_marbleized]weapon_knife_outdoor": 1,
        "[am_blackpearl_marbleized]weapon_knife_outdoor": 1,
        "[am_doppler_phase1]weapon_knife_outdoor": 1,
        "[am_doppler_phase2]weapon_knife_outdoor": 1,
        "[am_doppler_phase3]weapon_knife_outdoor": 1,
        "[am_doppler_phase4]weapon_knife_outdoor": 1,
        "[aq_damascus]weapon_knife_outdoor": 1,
        "[so_purple]weapon_knife_outdoor": 1,
        "[aq_steel_knife]weapon_knife_outdoor": 1,
    },
    "set_community_37_unusual": {
        "[glove_driver_brocade_crane_red]slick_gloves": 1,
        "[glove_driver_brocade_flower_red]slick_gloves": 1,
        "[glove_driver_dragon_scale_red]slick_gloves": 1,
        "[glove_driver_embroidered_flowers_teal]slick_gloves": 1,
        "[glove_driver_knit_argyle_green]slick_gloves": 1,
        "[glove_driver_ostrich_purple]slick_gloves": 1,
        "[glove_driver_scallop_metallic_blue]slick_gloves": 1,
        "[glove_driver_silk_dragon_white]slick_gloves": 1,

        "[glove_specialist_abstract_green]specialist_gloves": 1,
        "[glove_specialist_dragon_blue]specialist_gloves": 1,
        "[glove_specialist_graffiti_black]specialist_gloves": 1,
        "[glove_specialist_quilted_black]specialist_gloves": 1,
        "[glove_specialist_quilted_white]specialist_gloves": 1,
        "[glove_specialist_sunburst_red]specialist_gloves": 1,
        "[glove_specialist_wave_blue]specialist_gloves": 1,

        "[glove_sport_beadwork_diamonds_purple]sporty_gloves": 1,
        "[glove_sport_camo_winter]sporty_gloves": 1,
        "[glove_sport_flames_orange]sporty_gloves": 1,
        "[glove_sport_pinstripe_black]sporty_gloves": 1,
        "[glove_sport_racer_red]sporty_gloves": 1,
        "[glove_sport_tech_gradient_bright]sporty_gloves": 1,
        "[glove_sport_velvet_red]sporty_gloves": 1,
    },
}


SPECIAL_NOTES = {
    "crate-4017": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "Some skins (M4A4 Howl, USP-S Orion, MAC-10 Curse, CZ75-Auto Poison Dart, Dual Berettas Retribution and P90 Desert Warfare) were removed and replaced for others due to art theft.",
        }
    ],
    "crate-4458": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "It was replaced by Boston 2018 Minor Challengers with Flash Gaming (Holo/Foil) after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "crate-4461": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "It was replaced by Boston 2018 Minor Challengers with Flash Gaming Autograph Capsule after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "graffiti-2559": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "It was removed from the sale after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "skin-8aacf99e7f2f": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "This skin's appearance and rarity was changed from Covert to Contraband due to art theft. It also was removed from Huntsman Collection and Huntsman Weapon Case and is no longer obtainable except through trading or the Steam Market.",
        }
    ],
    "skin-c928639d51cb": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "It was removed because one of its creators was also involved with the M4A4 Howl art theft. This is no longer obtainable from the Huntsman Weapon Case, but remains part of The Huntsman Collection and still works with trade-up contracts.",
        }
    ],
    "skin-c98d2c843b36": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "It was removed because one of its creators was also involved with the M4A4 Howl art theft. This is no longer obtainable from the Huntsman Weapon Case, but remains part of The Huntsman Collection and still works with trade-up contracts.",
        }
    ],
    "skin-011747eede4b": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "It was removed because one of its creators was also involved with the M4A4 Howl art theft. This is no longer obtainable from the Huntsman Weapon Case, but remains part of The Huntsman Collection and still works with trade-up contracts.",
        }
    ],
    "skin-a503e5d8d0b7": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "It was removed because one of its creators was also involved with the M4A4 Howl art theft. This is no longer obtainable from the Huntsman Weapon Case, but remains part of The Huntsman Collection and still works with trade-up contracts.",
        }
    ],
    "skin-84742fb07c2b": [
        {
            "source": "https://steamcommunity.com/games/CSGO/announcements/detail/1751086783896069815",
            "text": "It was removed because one of its creators was also involved with the M4A4 Howl art theft. This is no longer obtainable from the Huntsman Weapon Case, but remains part of The Huntsman Collection and still works with trade-up contracts.",
        }
    ],
    "sticker-2528": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "It was removed from the sale after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "sticker-2529": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "The capsule that contains this was removed from the sale after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "sticker-2530": [
        {
            "source": "https://www.hltv.org/news/22359/tyloo-confirm-major-absence-replacement-to-come-from-asia-minor",
            "text": "The capsule that contains this was removed from the sale after Flash Gaming replaced Tyloo in the Boston 2018 major due to visa issues.",
        }
    ],
    "skin-8e8381232568": [
        {
            "source": "https://counterstrike.fandom.com/wiki/DreamHack_2013_Souvenir_Package#:~:text=It%20also%20has%20the%20potential%20to%20drop%20a%20bugged%20R8%20Revolver%20%7C%20Bone%20Mask%20from%20the%20Bank%20Collection%2C%20which%20was%20added%20to%20the%20package%20by%20mistake%20on%20December%208th%2C%202015%20in%20the%20R8%20Revolver%20update%2C%20when%20the%20R8%20Revolver%20%7C%20Amber%20Fade%20from%20the%20Dust%20II%20Collection%20was%20added.",
            "text": "Was added to the 'DreamHack 2013 Souvenir Package' by mistake making it the only souvenir in the Bank Collection.",
        }
    ],
}


CUSTOM_TRANSLATIONS = {
    "pt-BR": {
        "collectible_genuine": "{item_name} {genuine}",
        "rare_special": "{item_name} \u2605 | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} \u2605",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Lembrança) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Lembrança) | {keychain_name} | {highlight_name}",
    },
    "bg": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\u0421\u0443\u0432\u0435\u043d\u0438\u0440 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\u0421\u0443\u0432\u0435\u043d\u0438\u0440 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "cs": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Suven\u00fdr) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Suven\u00fdr) | {keychain_name} | {highlight_name}",
    },
    "da": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Souvenir) | {keychain_name} | {highlight_name}",
    },
    "nl": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "Souvenir {item_name} | {pattern} ({wear})",
        "highlight_charm": "Souvenir {charm_name} | {keychain_name} | {highlight_name}",
    },
    "en": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "Souvenir {item_name} | {pattern} ({wear})",
        "highlight_charm": "Souvenir {charm_name} | {keychain_name} | {highlight_name}",
    },
    "fi": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "Matkamuisto {item_name} | {pattern} ({wear})",
        "highlight_charm": "Matkamuisto {charm_name} | {keychain_name} | {highlight_name}",
    },
    "fr": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Souvenir) | {keychain_name} | {highlight_name}",
    },
    "de": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Souvenir) | {keychain_name} | {highlight_name}",
    },
    "el": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\u03a3\u03bf\u03c5\u03b2\u03b5\u03bd\u03af\u03c1 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\u03a3\u03bf\u03c5\u03b2\u03b5\u03bd\u03af\u03c1 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "hu": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Eml\u00e9kt\u00e1rgy) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Eml\u00e9kt\u00e1rgy) | {keychain_name} | {highlight_name}",
    },
    "it": {
        "collectible_genuine": "{item_name} {genuine}",
        "rare_special": "{item_name} \u2605 | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} \u2605 StatTrak\u2122 | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} \u2605",
        "rare_special_vanilla_stattrak": "{item_name} \u2605 StatTrak\u2122",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} StatTrak\u2122 | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Souvenir) | {keychain_name} | {highlight_name}",
    },
    "ja": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\u8a18\u5ff5\u54c1 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\u8a18\u5ff5\u54c1 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "ko": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605{item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\uae30\ub150\ud488 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\uae30\ub150\ud488 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "es-MX": {
        "collectible_genuine": "{item_name} {genuine}",
        "rare_special": "{item_name} \u2605 | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} \u2605 StatTrak\u2122 | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} \u2605",
        "rare_special_vanilla_stattrak": "{item_name} \u2605 StatTrak\u2122",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} StatTrak\u2122 | {pattern} ({wear})",
        "skin_souvenir": "{item_name} Recuerdo | {pattern} ({wear})",
        "highlight_charm": "{charm_name} Recuerdo | {keychain_name} | {highlight_name}",
    },
    "no": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Suvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Suvenir) | {keychain_name} | {highlight_name}",
    },
    "pl": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (pami\u0105tka) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (pami\u0105tka) | {keychain_name} | {highlight_name}",
    },
    "pt-PT": {
        "collectible_genuine": "{item_name} {genuine}",
        "rare_special": "{item_name} \u2605 | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} \u2605",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Lembrança) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Lembrança) | {keychain_name} | {highlight_name}",
    },
    "ro": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Suvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Suvenir) | {keychain_name} | {highlight_name}",
    },
    "ru": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\u0421\u0443\u0432\u0435\u043d\u0438\u0440\u043d\u044b\u0439 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\u0421\u0443\u0432\u0435\u043d\u0438\u0440\u043d\u044b\u0439 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "zh-CN": {
        "collectible_genuine": "{item_name}\uff08{genuine}\uff09",
        "rare_special": "{item_name}\uff08\u2605\uff09 | {pattern}",
        "rare_special_with_wear": "{item_name}\uff08\u2605\uff09 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name}\uff08\u2605 StatTrak\u2122\uff09 | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name}\uff08\u2605\uff09",
        "rare_special_vanilla_stattrak": "{item_name}\uff08\u2605 StatTrak\u2122\uff09",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name}\uff08StatTrak\u2122\uff09 | {pattern} ({wear})",
        "skin_souvenir": "{item_name}\uff08\u7eaa\u5ff5\u54c1\uff09 | {pattern} ({wear})",
        "highlight_charm": "{charm_name}\uff08\u7eaa\u5ff5\u54c1\uff09 | {keychain_name} | {highlight_name}",
    },
    "es-ES": {
        "collectible_genuine": "{item_name} {genuine}",
        "rare_special": "{item_name} \u2605 | {pattern}",
        "rare_special_with_wear": "{item_name} \u2605 | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} \u2605 StatTrak\u2122 | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} \u2605",
        "rare_special_vanilla_stattrak": "{item_name} \u2605 StatTrak\u2122",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} StatTrak\u2122 | {pattern} ({wear})",
        "skin_souvenir": "{item_name} Recuerdo | {pattern} ({wear})",
        "highlight_charm": "{charm_name} Recuerdo | {keychain_name} | {highlight_name}",
    },
    "sv": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "Souvenir {item_name} | {pattern} ({wear})",
        "highlight_charm": "Souvenir {charm_name} | {keychain_name} | {highlight_name}",
    },
    "zh-TW": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "\u7d00\u5ff5\u54c1 {item_name} | {pattern} ({wear})",
        "highlight_charm": "\u7d00\u5ff5\u54c1 {charm_name} | {keychain_name} | {highlight_name}",
    },
    "th": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (Souvenir) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (Souvenir) | {keychain_name} | {highlight_name}",
    },
    "tr": {
        "collectible_genuine": "{genuine} {item_name}",
        "rare_special": "\u2605 {item_name} | {pattern}",
        "rare_special_with_wear": "\u2605 {item_name} | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "\u2605 StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "rare_special_vanilla": "\u2605 {item_name}",
        "rare_special_vanilla_stattrak": "\u2605 StatTrak\u2122 {item_name}",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "StatTrak\u2122 {item_name} | {pattern} ({wear})",
        "skin_souvenir": "Hat\u0131ra {item_name} | {pattern} ({wear})",
        "highlight_charm": "Hat\u0131ra {charm_name} | {keychain_name} | {highlight_name}",
    },
    "uk": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (\u0421\u0443\u0432\u0435\u043d\u0456\u0440) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (\u0421\u0443\u0432\u0435\u043d\u0456\u0440) | {keychain_name} | {highlight_name}",
    },
    "vi": {
        "collectible_genuine": "{item_name} ({genuine})",
        "rare_special": "{item_name} (\u2605) | {pattern}",
        "rare_special_with_wear": "{item_name} (\u2605) | {pattern} ({wear})",
        "rare_special_with_wear_stattrak": "{item_name} (\u2605 StatTrak\u2122) | {pattern} ({wear})",
        "rare_special_vanilla": "{item_name} (\u2605)",
        "rare_special_vanilla_stattrak": "{item_name} (\u2605 StatTrak\u2122)",
        "skin": "{item_name} | {pattern} ({wear})",
        "skin_stattrak": "{item_name} (StatTrak\u2122) | {pattern} ({wear})",
        "skin_souvenir": "{item_name} (L\u01b0u ni\u1ec7m) | {pattern} ({wear})",
        "highlight_charm": "{charm_name} (L\u01b0u ni\u1ec7m) | {keychain_name} | {highlight_name}",
    },
}
